replicaCount: 1  # Adjust to 2+ if needed and resources permit

image:
  repository: arunkumar2255/nodejs-latest
  pullPolicy: Always
  tag: "v.89"

service:
  type: NodePort
  port: 5000

env:
  PORT: 5000
  MONGODB_URI: ""

resources:
  requests:
    memory: "32Mi"  # Reduced memory requests
    cpu: "100m"     # Reduced CPU requests
  limits:
    memory: "64Mi"  # Reduced memory limits
    cpu: "250m"     # Reduced CPU limits
