replicaCount: 1  # Adjust to 2+ if needed and resources permit

image:
  repository: asia-east1-docker.pkg.dev/gcp-poc-442512/my-repo/my-app
  pullPolicy: Always
  tag: latest


service:
  type: NodePort
  port: 5000

env:
  PORT: 5000
  MONGODB_URI: ""

resources:
  requests:
    memory: "32Mi"  # Reduced memory requests
    cpu: "100m"     # Reduced CPU requests
  limits:
    memory: "64Mi"  # Reduced memory limits
    cpu: "250m"     # Reduced CPU limits
