replicaCount: 1

image:
  repository: arunkumar2255/nodejs-latest
  pullPolicy: Always
  tag: "v.89"

service:
  type: NodePort
  port: 5000

env:
  PORT: 5000
  MONGODB_URI: ""

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
