name: Deploy Application to GKE using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy-gke:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the application code
      - name: Check out Application Repository
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Install gke-gcloud-auth-plugin via gcloud
        run: |
         gcloud components install gke-gcloud-auth-plugin




      # Set up GKE kubectl credentials
      - name: 'Configure GKE credentials'
        run: |
          gcloud container clusters get-credentials my-private-cluster --zone asia-east1-c --project gcp-poc-442512

      # Verify kubectl setup
      - name: 'Verify kubectl setup'
        run: kubectl get nodes

      


