name: GCP Login, Image Building, Push To GCR, Deploy In GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    # Step 3: Authenticate Docker to Artifact Registry
    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker asia-east1-docker.pkg.dev

    # Step 4: Build Docker Image
    - name: Build Docker Image
      id: build
      run: |
        IMAGE_NAME=asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app
        docker build -t $IMAGE_NAME ./AppRes
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV

    # Step 5: Push Docker Image to Artifact Registry
    - name: Push Docker Image to Artifact Registry
      run: |
        docker push ${{ env.image }}

    # Step 6: Verify Cluster Details
    - name: Verify GKE Cluster
      run: |
        gcloud container clusters describe my-private-cluster \
          --zone asia-east1-c \
          --project ${{ secrets.GCP_PROJECT_ID }}

    # Step 7: Set up GKE Kubectl
    - name: Set up GKE Kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: my-private-cluster
        location: asia-east1-c
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        use_internal_ip: true

    # Step 8: Deploy Using Helm
    - name: Deploy to GKE
      run: |
        helm upgrade --install my-app ./helm/chart \
          --namespace default \
          --set image.repository=${{ env.image }} \
          --set image.tag=latest
