name: Deploy Application to GKE using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy-gke:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the application code
      - name: Check out Application Repository
        uses: actions/checkout@v3

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Authenticate to Google Cloud
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Add Google Cloud SDK repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          sudo apt-get update

      - name: Install google-cloud-sdk and gke-gcloud-auth-plugin
        run: |
         sudo apt-get update
         sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Verify gke-gcloud-auth-plugin installation
        run: |
         gke-gcloud-auth-plugin --version






      # Set up GKE kubectl credentials
      - name: 'Configure GKE credentials'
        run: |
          gcloud container clusters get-credentials my-private-cluster --zone asia-east1-c --project gcp-poc-442512

      # Verify kubectl setup
      - name: 'Verify kubectl setup'
        run: kubectl get nodes

      


