name: GCP Login, Image Building, Push To GCR, Deploy In GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to Artifact Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Authenticate Docker to Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build Docker Image
      id: build
      run: |
        IMAGE_NAME=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-artifact-repo/my-app
        docker build -t $IMAGE_NAME ./AppRes
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Push Docker Image to Artifact Registry
      run: |
        docker push ${{ env.image }}
